#!/bin/bash

file_he='tmp/1-file_list-helpers.txt'
file_mo='tmp/1-file_list-models.txt'
file_co='tmp/1-file_list-controllers.txt'
file_vi='tmp/1-file_list-views.txt'
file_ma='tmp/1-file_list-mailers.txt'
file_jo='tmp/1-file_list-jobs.txt'

sh pg-start.sh

echo '------------------------------------'
echo 'Listing the helper files in the file'
echo $file_he
echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_he
echo '-------------------' >> $file_he
echo 'HELPERS' >> $file_he
tree test/helpers >> $file_he
echo '' >> $file_he
tree app/helpers >> $file_he
echo '' >> $file_he

echo '-------------------------------'
echo 'Listing the model files in file'
echo $file_mo
echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_mo
echo '------' >> $file_mo
echo 'MODELS' >> $file_mo
tree test/unit >> $file_mo
echo '' >> $file_mo
tree test/fixtures >> $file_mo
echo '' >> $file_mo
tree app/models >> $file_mo

echo '------------------------------------'
echo 'Listing the controller files in file'
echo $file_co
echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_co
echo '-----------' >> $file_co
echo 'CONTROLLERS' >> $file_co
tree test/functional >> $file_co
echo '' >> $file_co
tree app/controllers >> $file_co

echo '--------------------------------'
echo 'Listing the mailer files in file'
echo $file_ma
echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_ma
echo '-----------' >> $file_ma
echo 'MAILERS' >> $file_ma
tree test/emails >> $file_ma
echo '' >> $file_ma
tree test/mailers >> $file_ma
echo '' >> $file_ma
tree app/mailers >> $file_ma

echo '------------------------------'
echo 'Listing the jobs files in file'
echo $file_jo
echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_jo
echo '----' >> $file_jo
echo 'JOBS' >> $file_jo
tree test/jobs >> $file_jo
echo '' >> $file_jo
tree app/jobs >> $file_jo

echo '----------------------------------------------------'
echo 'Listing the view files and integration tests in file'
echo $file_vi
echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_vi
echo '---------------------------' >> $file_vi
echo 'VIEWS AND INTEGRATION TESTS' >> $file_vi
echo '' >> $file_vi
echo '------------' >> $file_vi
echo 'rails routes' >> $file_vi
rails routes >> $file_vi
echo '----------------' >> $file_vi
echo 'config/routes.rb' >> $file_vi
cat config/routes.rb >> $file_vi
echo '----------------' >> $file_vi
tree test/integration >> $file_vi
echo '' >> $file_vi
tree app/views >> $file_vi

echo 'FINISHED compiling the list of files that make up the MVC structure'
echo '-------------------------------------------------------------------'

echo '******************************'
echo 'outline-short.sh OUTPUT FILES:'
echo $file_he
echo $file_mo
echo $file_co
echo $file_vi
echo $file_ma
echo $file_jo
echo
